// <auto-generated />
namespace LocationAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20181211 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20181211));
        
        string IMigrationMetadata.Id
        {
            get { return "201812110458489_20181211"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
